name: Build Wheels

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: wheel-building  # Requires manual approval
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.16.2

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        # Build for CPython 3.11-3.14
        CIBW_BUILD: cp311-* cp312-* cp313-* cp314-*

        # Skip 32-bit builds and musllinux (for now)
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"

        # Linux: Use manylinux with OpenBLAS
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_BEFORE_BUILD_LINUX: |
          yum install -y openblas-devel lapack-devel
          pip install meson ninja numpy

        # macOS: Use Accelerate framework
        CIBW_BEFORE_BUILD_MACOS: |
          brew install ninja meson
          pip install numpy

        # Windows: Use clang from conda-forge
        CIBW_BEFORE_BUILD_WINDOWS: |
          pip install meson ninja numpy
          # Note: This may need refinement for clang setup

        # Test the built wheels
        CIBW_TEST_REQUIRES: pytest numpy
        CIBW_TEST_COMMAND: pytest {project}/python/tests/

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl
        retention-days: 30  # Keep artifacts for 30 days
