name: Publish to PyPI (Token-based - Legacy)

# LEGACY METHOD: Uses API tokens stored in GitHub Secrets
# Only use if trusted publishing doesn't work
#
# Setup:
# 1. Generate API token at https://pypi.org/manage/account/token/
# 2. Add to GitHub Secrets as PYPI_API_TOKEN
# 3. Scope token to 'slicutlet' project only (after first upload)

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      run_id:
        description: 'Build Wheels workflow run ID (from Actions tab)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish-pypi-token:
    runs-on: ubuntu-latest
    environment:
      name: pypi-token
      url: https://pypi.org/project/slicutlet/

    steps:
    - name: Download artifacts from build workflow
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ inputs.run_id }}
        pattern: wheels-*
        merge-multiple: true
        path: dist

    - name: List downloaded wheels
      run: ls -lah dist/

    - name: Publish to PyPI (Token)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print-hash: true
        verbose: true
