name: Test Windows (Conda + LLVM/clang)

on:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.13'
        channels: conda-forge
        channel-priority: strict

    - name: Install dependencies with conda
      shell: bash -l {0}
      run: |
        conda install -y \
          meson \
          ninja \
          numpy \
          pytest \
          openblas \
          clang \
          llvm-tools \
          lld

    - name: Build SLICUTLET (using LLVM/clang with MinGW target)
      shell: bash -l {0}
      run: |
        # Force clang to target MinGW-w64 instead of MSVC for C11 complex support
        export CC="clang --target=x86_64-w64-mingw32"
        export CXX="clang++ --target=x86_64-w64-mingw32"
        meson setup build -Dpython=true
        meson install -C build --destdir="${PWD}/build-install"

    - name: Run tests
      shell: bash -l {0}
      run: |
        export PYTHONPATH="${PWD}/build-install/usr/local/lib/python3.13/site-packages"
        export PATH="${PWD}/build-install/usr/local/bin:${PATH}"
        pytest python/tests/ -v

    - name: Check compiler used
      shell: bash -l {0}
      run: |
        cat build/meson-logs/meson-log.txt | grep -i "compiler"
