name: Test Linux (Basic)

on:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ninja-build \
          libopenblas-dev \
          liblapack-dev \
          pkg-config

    - name: Install Python dependencies
      run: |
        pip install meson numpy pytest

    - name: Build SLICUTLET
      run: |
        meson setup build -Dpython=true
        meson install -C build --destdir="${PWD}/build-install"

    - name: Run tests
      run: |
        export PYTHONPATH="${PWD}/build-install/usr/local/lib/python3.13/site-packages"
        export LD_LIBRARY_PATH="${PWD}/build-install/usr/local/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
        pytest python/tests/ -v
